### ISSUE TITLE
Error retrieving translation : unable to parse 'null' as integer

### ISSUE THREAD

**Issue by virinchyp** [boatmeme/microsoft-translator-java-api#44]
i am just trying to run the bing translation java api  v0.6 in android 2.3.3 performing an async task as here 
https://github.com/rmtheis/android-ocr and getting the following error retrieving the translated text.

E/TranslatorBing(30659): Caught exeption in translation request.

 W/System.err(30659): java.lang.Exception: [microsoft-translator-api] Error retrieving translation : unable to parse 'null' as integer

 W/System.err(30659): at com.memetix.mst.MicrosoftTranslatorAPI.retrieveString(MicrosoftTranslatorAPI.java:199)

 W/System.err(30659):   at com.memetix.mst.translate.Translate.execute(Translate.java:61)

W/System.err(30659):    at edu.sfsu.cs.orange.ocr.language.TranslatorBing.translate(TranslatorBing.java:42)

W/System.err(30659):    at edu.sfsu.cs.orange.ocr.language.Translator.translate(Translator.java:49)

 W/System.err(30659):   at edu.sfsu.cs.orange.ocr.language.TranslateAsyncTask.doInBackground(TranslateAsyncTask.java:58)

 W/System.err(30659):   at edu.sfsu.cs.orange.ocr.language.TranslateAsyncTask.doInBackground(TranslateAsyncTask.java:1)

W/System.err(30659):    at android.os.AsyncTask$2.call(AsyncTask.java:185)
01-21 16:58:38.085: W/System.err(30659):    at 

java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:306)

W/System.err(30659):    at java.util.concurrent.FutureTask.run(FutureTask.java:138)
01-21 16:58:38.085: W/System.err(30659):    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1088)

W/System.err(30659):    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:581)

W/System.err(30659):    at java.lang.Thread.run(Thread.java:1019)

W/System.err(30659): Caused by: java.lang.NumberFormatException: unable to parse 'null' as integer

 W/System.err(30659):   at java.lang.Integer.parseInt(Integer.java:356)

W/System.err(30659):    at java.lang.Integer.parseInt(Integer.java:332)

W/System.err(30659):    at com.memetix.mst.MicrosoftTranslatorAPI.retrieveResponse(MicrosoftTranslatorAPI.java:158)

W/System.err(30659):    at com.memetix.mst.MicrosoftTranslatorAPI.retrieveString(MicrosoftTranslatorAPI.java:196)

 W/System.err(30659):   ... 11 more

TranslateAsyncTask(30659): FAILURE

**Comment by ariefstephen** [comment]
i get the same problem here, have you resolved it? please tell me hoe to fix it. i'm confused now.
